Repository IPG-Automotive-UK/react-ui, pull requests merged in 2021-11, with the labels that each got.

#255 Migrate to mui 5
  .eslintrc
  .prettierrc
  .storybook/main.js
  package-lock.json
  package.json
  src/Copyright/Copyright.js
  src/Loading/Loading.js
  src/LoginForm/LoginForm.js
  src/NoLicense/NoLicense.js
  src/PasswordChangeDialog/PasswordChangeDialog.js
  src/PasswordChangeDialog/PasswordChangeDialog.stories.js
  src/PasswordChangeForm/PasswordChangeForm.js
  src/PasswordResetForm/PasswordResetForm.js
  src/RegistrationForm/RegistrationForm.js
  src/SearchBar/SearchBar.js
  src/Select/Select.js
  src/Sidebar/Sidebar.js
  src/Sidebar/SidebarDivider/SidebarDivider.js
  src/Sidebar/SidebarItem/SidebarItem.js
  src/Sidebar/SidebarItem/SidebarItem.stories.js
  src/Sidebar/SidebarItem/SidebarItem.test.js
  src/Snackbar/Snackbar.js
  src/Snackbar/Snackbar.stories.js
  src/SwitchField/SwitchField.js
  src/ThemeProvider/ThemeProvider.js
  src/ThemeProvider/ThemeProvider.test.js
  src/UserMenu/UserMenu.js
  src/UserMenu/UserMenu.stories.js
Labels: dependencies

#256 Feature/hide sidebar logo version
  src/Sidebar/Sidebar.js
  src/Sidebar/Sidebar.stories.js
  src/Sidebar/Sidebar.test.js
Labels: enhancement

#265 SidebarItem styling props
  src/Sidebar/SidebarItem/SidebarItem.js
  src/Sidebar/SidebarItem/SidebarItem.stories.js
Labels: enhancement

#264 Feature/slider component
  src/Slider/Slider.js
  src/Slider/Slider.stories.js
  src/Slider/Slider.test.js
  src/Slider/index.js
Labels: enhancement

#266 Feature/colorpicker
  package-lock.json
  package.json
  src/Color/Color.js
  src/Color/Color.stories.js
  src/Color/Color.test.js
  src/Color/index.js
Labels: enhancement

#267 Add disabled property to Slider
  src/Slider/Slider.js
  src/Slider/Slider.stories.js
Labels: enhancement

#268 Feature/text and number fields
  src/NumberField/NumberField.js
  src/NumberField/NumberField.stories.js
  src/NumberField/NumberField.test.js
  src/NumberField/index.js
  src/TextField/TextField.js
  src/TextField/TextField.stories.js
  src/TextField/TextField.test.js
  src/TextField/index.js
  src/index.js
Labels: enhancement

#275 Radio buttons group
  src/RadioButtons/RadioButtons.js
  src/RadioButtons/RadioButtons.stories.js
  src/RadioButtons/RadioButtons.test.js
  src/RadioButtons/index.js
  src/index.js
Labels: enhancement

#278 Bug/color swatch border
  src/Color/Color.js
Labels: bug

#279 Feature/text align horizontal
  src/AlignHorizontal/AlignHorizontal.js
  src/AlignHorizontal/AlignHorizontal.stories.js
  src/AlignHorizontal/AlignHorizontal.test.js
  src/AlignHorizontal/index.js
  src/Copyright/Copyright.stories.js
  src/NumberField/NumberField.stories.js
  src/TextField/TextField.stories.js
  src/index.js
Labels: enhancement

#280 Font style component
  src/FontStyle/FontStyle.js
  src/FontStyle/FontStyle.stories.js
  src/FontStyle/FontStyle.test.js
  src/FontStyle/index.js
  src/index.js
Labels: enhancement

#281 Feature/honor min max in numberfield
  src/NumberField/NumberField.js
  src/NumberField/NumberField.stories.js
  src/TextField/TextField.js
Labels: bug

#282 Fix vertical slider
  src/Slider/Slider.js
  src/Slider/Slider.stories.js
Labels: bug

#289 Expose checkbox style
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.stories.js
Labels: enhancement
