Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-08, with the labels that each got.

#687 updated deps to latest version
  package-lock.json
  package.json
Labels: dependencies

#680 Status card component
  src/Status/StatusCard/StatusCard.stories.tsx
  src/Status/StatusCard/StatusCard.test.tsx
  src/Status/StatusCard/StatusCard.tsx
  src/Status/StatusCard/StatusCard.types.ts
  src/Status/StatusCard/index.ts
  src/Status/StatusIcon/StatusIcon.js
  src/Status/StatusIcon/StatusIcon.stories.tsx
  src/Status/StatusIcon/StatusIcon.test.js
  src/Status/StatusIcon/StatusIcon.test.tsx
  src/Status/StatusIcon/StatusIcon.tsx
  src/Status/StatusIcon/StatusIcon.types.ts
  src/Status/StatusIcon/index.js
  src/Status/StatusIcon/index.ts
  src/Status/StatusLabel/StatusLabel.js
  src/Status/StatusLabel/StatusLabel.stories.js
  src/Status/StatusLabel/StatusLabel.stories.tsx
  src/Status/StatusLabel/StatusLabel.test.js
  src/Status/StatusLabel/StatusLabel.test.tsx
  src/Status/StatusLabel/StatusLabel.tsx
  src/Status/StatusLabel/StatusLabel.types.ts
  src/Status/StatusLabel/index.js
  src/Status/StatusLabel/index.ts
  src/Status/StatusMessage/StatusMessage.js
  src/Status/StatusMessage/StatusMessage.stories.js
  src/Status/StatusMessage/StatusMessage.test.js
  src/Status/StatusMessage/index.js
  src/Status/index.js
  src/Status/index.ts
  src/Status/statuses.ts
  src/index.ts
Labels: enhancement

#689 width and border radius updated as figma
  src/Status/StatusCard/StatusCard.tsx
Labels: enhancement

#690 updated TextField component to support multiline
  src/TextField/TextField.stories.tsx
  src/TextField/TextField.test.tsx
  src/TextField/TextField.tsx
  src/TextField/TextField.types.ts
Labels: enhancement

#691 TD-2038 color of the alert title in dark mode mismatched
  src/ThemeProvider/ThemeProvider.tsx
Labels: enhancement

#692 TD-2067 DeletableList component
  src/DeletableList/DeletableList.stories.tsx
  src/DeletableList/DeletableList.test.tsx
  src/DeletableList/DeletableList.tsx
  src/DeletableList/DeletableList.types.ts
  src/DeletableList/index.ts
  src/TransferList/TransferList.stories.tsx
  src/TransferList/TransferList.test.tsx
  src/TransferList/TransferList.tsx
  src/TransferList/TransferList.types.ts
  src/TransferList/index.js
  src/TransferList/index.ts
  src/index.ts
Labels: enhancement

#694 TD-2065 Vehicle Select component
  src/Autocomplete/Autocomplete.stories.tsx
  src/FontPicker/FontPicker.stories.js
  src/LabelSelector/LabelSelector.stories.js
  src/Select/Select.stories.js
  src/VehicleSelect/VehicleSelect.stories.tsx
  src/VehicleSelect/VehicleSelect.test.tsx
  src/VehicleSelect/VehicleSelect.tsx
  src/VehicleSelect/VehicleSelect.types.ts
  src/VehicleSelect/index.ts
  src/index.ts
Labels: enhancement

#695 TD 2069 vehicle select dialog
  .github/workflows/test.yml
  src/ActionDialog/ActionDialog.stories.tsx
  src/Autocomplete/Autocomplete.stories.tsx
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
  src/DialogTitle/DialogTitle.stories.js
  src/VehicleSelect/VehicleSelect.test.tsx
  src/VehicleSelect/VehicleSelect.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.stories.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.test.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.types.ts
  src/VehicleSelectDialog/index.ts
  src/index.ts
Labels: enhancement

#696 Fixed inconsistency with project and projectCode
  src/VehicleSelect/VehicleSelect.stories.tsx
  src/VehicleSelect/VehicleSelect.test.tsx
  src/VehicleSelect/VehicleSelect.tsx
  src/VehicleSelect/VehicleSelect.types.ts
  src/VehicleSelectDialog/VehicleSelectDialog.tsx
Labels: bug

#697 Fix spread syntax bundling error with VehicleSelect
  src/VehicleSelect/VehicleSelect.tsx
Labels: bug
