Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-04, with the labels that each got.

#562 ModelButtonImage component
  src/ModelButtonImage/ModelButtonImage.js
  src/ModelButtonImage/ModelButtonImage.stories.js
  src/ModelButtonImage/ModelButtonImage.test.js
  src/ModelButtonImage/index.js
  src/index.js
  static/ModelButtonSampleImg.svg
Labels: enhancement

#564 Feature/TD-1356,TD-1238-generic-dialog-component
  src/ActionDialog/ActionDialog.js
  src/ActionDialog/ActionDialog.stories.js
  src/ActionDialog/ActionDialog.test.js
  src/ActionDialog/index.js
  src/AlignVertical/AlignVertical.js
  src/index.js
Labels: enhancement

#568 removed and added styling dialog component to outside actiondialog
  src/ActionDialog/ActionDialog.js
Labels: bug

#570 Bugfix/summary card more options click to close
  src/Card/SummaryCard/SummaryCard.js
  src/Card/SummaryCard/SummaryCard.stories.js
  src/Card/SummaryCard/SummaryCard.test.js
Labels: bug

#572 Bugfix/label selector long string
  src/LabelSelector/LabelSelector.js
  src/LabelSelector/LabelSelector.stories.js
  src/LabelSelector/LabelSelector.test.js
  src/NoWrapTypography/NoWrapTypography.js
Labels: bug

#571 Correct LabelChip font
  src/LabelSelector/LabelChip/LabelChip.js
Labels: bug

#574 Card component fixes
  src/Card/DetailCard/DetailCard.js
  src/Card/DetailCard/DetailCard.stories.js
  src/Card/FileCard/FileCard.js
  src/Card/TableCard/TableCard.js
  src/Card/TableCard/TableCard.stories.js
Labels: enhancement

#573 Add more tests to react-ui components
  package-lock.json
  package.json
  src/AppHeader/AppHeader.js
  src/AppHeader/AppHeader.test.js
  src/AppLayout/AppLayout.js
  src/AppLayout/AppLayout.test.js
Labels: enhancement

#576 Dependent bot updates/20 apr2023
  package-lock.json
  package.json
  src/Card/SummaryCard/SummaryCard.test.js
  src/ConfirmProvider/ConfirmProvider.test.js
Labels: dependencies

#575 Feature/typescript infrastructure
  .eslintrc
  package-lock.json
  package.json
  src/AlignHorizontal/AlignHorizontal.stories.js
  src/AlignHorizontal/AlignHorizontal.stories.tsx
  src/AlignHorizontal/AlignHorizontal.test.tsx
  src/AlignHorizontal/AlignHorizontal.tsx
  src/AlignHorizontal/AlignHorizontal.types.ts
  src/AlignHorizontal/index.js
  src/AlignHorizontal/index.ts
  src/index.ts
  src/jest.config.ts
  tsconfig.json
Labels: documentation, enhancement, dependencies

#578 Removed NoLicense component
  src/NoLicense/NoLicense.js
  src/NoLicense/NoLicense.stories.js
  src/NoLicense/NoLicense.test.js
  src/NoLicense/index.js
  src/index.ts
Labels: enhancement

#579 Moved ConfirmProvider into AppLayout
  src/AppHeader/AppHeader.stories.tsx
  src/AppHeader/AppHeader.test.tsx
  src/AppHeader/AppHeader.tsx
  src/AppHeader/AppHeader.types.ts
  src/AppHeader/index.js
  src/AppHeader/index.ts
  src/AppLauncher/AppLauncher.stories.tsx
  src/AppLauncher/AppLauncher.test.tsx
  src/AppLauncher/AppLauncher.tsx
  src/AppLauncher/AppLauncher.types.ts
  src/AppLauncher/index.js
  src/AppLauncher/index.ts
  src/AppLayout/AppLayout.stories.tsx
  src/AppLayout/AppLayout.test.tsx
  src/AppLayout/AppLayout.tsx
  src/AppLayout/AppLayout.types.ts
  src/Card/SummaryCard/SummaryCard.js
  src/Card/SummaryCard/SummaryCard.stories.js
  src/NoWrapTypography/NoWrapTypography.stories.tsx
  src/NoWrapTypography/NoWrapTypography.test.tsx
  src/NoWrapTypography/NoWrapTypography.tsx
  src/NoWrapTypography/NoWrapTypography.types.ts
  src/NoWrapTypography/index.js
  src/NoWrapTypography/index.ts
  src/Sidebar/Sidebar.stories.tsx
  src/Sidebar/Sidebar.test.tsx
  src/Sidebar/Sidebar.tsx
  src/Sidebar/Sidebar.types.ts
  src/Sidebar/SidebarDivider/SidebarDivider.stories.tsx
  src/Sidebar/SidebarDivider/SidebarDivider.test.tsx
  src/Sidebar/SidebarDivider/SidebarDivider.tsx
  src/Sidebar/SidebarDivider/index.ts
  src/Sidebar/SidebarItem/SidebarItem.stories.tsx
  src/Sidebar/SidebarItem/SidebarItem.test.tsx
  src/Sidebar/SidebarItem/SidebarItem.tsx
  src/Sidebar/SidebarItem/SidebarItem.types.ts
  src/Sidebar/SidebarItem/index.js
  src/Sidebar/SidebarItem/index.ts
  src/Sidebar/index.ts
  src/UserMenu/UserMenu.stories.tsx
  src/UserMenu/UserMenu.test.tsx
  src/UserMenu/UserMenu.tsx
  src/UserMenu/UserMenu.types.ts
  src/UserMenu/index.js
  src/UserMenu/index.ts
  src/index.ts
Labels: enhancement
