Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-06, with the labels that each got.

#627 updated deps to latest versions
  package-lock.json
  package.json
Labels: dependencies

#629 Fix console error for userMenu Component
  src/UserMenu/UserMenu.tsx
  src/UserMenu/UserMenu.types.ts
Labels: bug

#635 TD-1810
  src/Card/DetailCard/DetailCard.stories.tsx
  src/Card/DetailCard/DetailCard.test.tsx
  src/Card/DetailCard/DetailCard.tsx
  src/Card/DetailCard/DetailCard.types.ts
  src/Card/DetailCard/index.js
  src/Card/DetailCard/index.ts
  src/Card/FileCard/FileCard.test.tsx
  src/Card/FileCard/FileCard.tsx
  src/Card/FileCard/FileCard.types.ts
  src/Card/FileCard/index.js
  src/Card/FileCard/index.ts
  src/Card/index.ts
  src/Common.types.ts
  src/SearchBar/SearchBar.stories.tsx
  src/SearchBar/SearchBar.test.tsx
  src/SearchBar/SearchBar.tsx
  src/SearchBar/SearchBar.types.ts
  src/SearchBar/index.js
  src/SearchBar/index.ts
  src/index.ts
Labels: enhancement

#638 Fix for SVGIcon in latest @mui/material
  package-lock.json
  package.json
  src/SvgIcons/IpgLogo/IpgLogo.tsx
  src/SvgIcons/VirtoBuild/VirtoBuild.js
  src/SvgIcons/VirtoData/VirtoData.js
  src/SvgIcons/VirtoFleet/VirtoFleet.js
  src/SvgIcons/VirtoID/VirtoID.js
  src/SvgIcons/VirtoLogo/VirtoLogo.js
  src/SvgIcons/VirtoModel/VirtoModel.js
  src/SvgIcons/VirtoResult/VirtoResult.js
  src/SvgIcons/VirtoScene/VirtoScene.js
  src/SvgIcons/VirtoTest/VirtoTest.js
  src/SvgIcons/VirtoVehicle/VirtoVehicle.js
Labels: bug, dependencies
