Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-12, with the labels that each got.

#774 Adding a CONTRIBUTING file with a strategy for implementing tests
  CONTRIBUTING.md
Labels: documentation

#773 Migrating flaky tests to Playwright
  package-lock.json
  src/VehicleSelect/VehicleSelect.spec.tsx
  src/VehicleSelect/VehicleSelect.test.tsx
Labels: enhancement, dependencies

#772 UserAvatar font-size consistency
  src/UserAvatar/UserAvatar.test.tsx
  src/UserAvatar/UserAvatar.tsx
  src/UserAvatar/UserAvatar.types.ts
  src/UserMenu/UserMenu.test.tsx
  src/UserMenu/UserMenu.tsx
Labels: bug
