Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-10, with the labels that each got.

#748 Playwright runner fails on GitHub actions
  .github/workflows/test.yml
  package-lock.json
  package.json
  serve-storybook.js
Labels: bug

#751 Bug/vehicle select component test fix
  src/VehicleSelect/VehicleSelect.test.tsx
Labels: bug

#749 updated to latest versions
  package-lock.json
  package.json
Labels: dependencies

#730 SurfacePlot Component
  .github/workflows/test.yml
  package-lock.json
  package.json
  playwright.config.ts
  src/ConditionalDialog/ConditionalDialog.spec.ts
  src/ConditionalDialog/ConditionalDialog.stories.tsx
  src/ConditionalDialog/ConditionalDialog.tsx
  src/ConditionalDialog/ConditionalDialog.types.ts
  src/ConditionalDialog/index.ts
  src/LinePlot/LinePlot.tsx
  src/SurfacePlot/SurfacePlot.spec.tsx
  src/SurfacePlot/SurfacePlot.stories.tsx
  src/SurfacePlot/SurfacePlot.tsx
  src/SurfacePlot/SurfacePlot.types.ts
  src/SurfacePlot/SurfacePlotClientOnly.tsx
  src/SurfacePlot/index.ts
  src/index.ts
  src/utils/plotlyConfig.ts
Labels: enhancement

#757 TD-2221 New status "No Metrics" for Card Status
  src/Status/StatusCard/StatusCard.test.tsx
  src/Status/StatusCard/StatusCard.types.ts
Labels: bug

#759 Bug Fix - useColorMap incorrect typedef
  src/UserAvatar/index.d.ts
Labels: bug

#761 TD-2051 New Prop and component conversion to typescript
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.test.tsx
  src/FileUploader/FileUploader.tsx
  src/FileUploader/FileUploader.types.ts
  src/FileUploader/index.d.ts
  src/FileUploader/index.js
  src/FileUploader/index.tsx
  src/ImageUploader/ImageUploader.stories.tsx
  src/ImageUploader/ImageUploader.test.tsx
  src/ImageUploader/ImageUploader.tsx
  src/ImageUploader/ImageUploader.types.tsx
  src/ImageUploader/index.d.ts
  src/ImageUploader/index.js
  src/ImageUploader/index.tsx
Labels: enhancement

#760 LoadErrorMessage component
  src/LoadErrorMessage/LoadErrorMessage.spec.tsx
  src/LoadErrorMessage/LoadErrorMessage.stories.tsx
  src/LoadErrorMessage/LoadErrorMessage.tsx
  src/LoadErrorMessage/LoadErrorMessage.types.ts
  src/LoadErrorMessage/index.ts
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.tsx
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.types.ts
  src/SvgIcons/VirtoMascots/VirtoThinking/index.ts
  src/SvgIcons/index.ts
  src/index.ts
  static/VirtoThinking.svg
Labels: enhancement
