Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-09, with the labels that each got.

#718 Publish source code
  .gitignore
  package-lock.json
  package.json
Labels: dependencies

#724 DeletableList delete icon button can only delete the list item
  src/DeletableList/DeletableList.test.tsx
  src/DeletableList/DeletableList.tsx
  src/TransferList/TransferList.test.tsx
Labels: bug

#723 TD-2134 LinePlot component
  .github/workflows/test.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  src/ClientOnly/ClientOnly.tsx
  src/ClientOnly/ClientOnly.types.tsx
  src/ClientOnly/index.ts
  src/LinePlot/LinePlot.spec.tsx
  src/LinePlot/LinePlot.stories.tsx
  src/LinePlot/LinePlot.test.tsx
  src/LinePlot/LinePlot.tsx
  src/LinePlot/LinePlot.types.ts
  src/LinePlot/LinePlotClientOnly.tsx
  src/LinePlot/index.ts
  src/TransferList/TransferList.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.tsx
  src/index.ts
Labels: enhancement

#727 September dependency updates
  package-lock.json
  package.json
Labels: dependencies

#729 TD-2097 New status icon and label for "No Metrics"
  src/Status/StatusIcon/StatusIcon.stories.tsx
  src/Status/StatusIcon/StatusIcon.types.ts
  src/Status/StatusLabel/StatusLabel.stories.tsx
  src/Status/StatusLabel/StatusLabel.types.ts
  src/Status/statuses.ts
Labels: enhancement
