Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-05, with the labels that each got.

#580 Bugfix/light dark mode toggle
  src/ThemeProvider/ThemeContext.js
  src/ThemeProvider/ThemeContext.tsx
  src/ThemeProvider/ThemeProvider.test.js
  src/ThemeProvider/ThemeProvider.test.tsx
  src/ThemeProvider/ThemeProvider.tsx
  src/ThemeProvider/ThemeProvider.types.ts
  src/ThemeProvider/index.ts
  src/ThemeProvider/useTheme.ts
  src/index.ts
Labels: bug

#600 Dependency updates 2nd may2023
  package-lock.json
  package.json
  src/AppLayout/AppLayout.tsx
Labels: dependencies

#583 Feature/ipg logo mode property
  src/Sidebar/Sidebar.stories.tsx
  src/Sidebar/Sidebar.tsx
  src/Sidebar/SidebarItem/SidebarItem.stories.tsx
  src/Sidebar/SidebarItem/SidebarItem.tsx
  src/Sidebar/SidebarItem/SidebarItem.types.ts
  src/SvgIcons/IpgLogo/IpgLogo.js
  src/SvgIcons/IpgLogo/IpgLogo.stories.js
  src/SvgIcons/IpgLogo/IpgLogo.stories.tsx
  src/SvgIcons/IpgLogo/IpgLogo.test.tsx
  src/SvgIcons/IpgLogo/IpgLogo.tsx
  src/SvgIcons/IpgLogo/IpgLogo.types.ts
  src/SvgIcons/IpgLogo/index.js
  src/SvgIcons/IpgLogo/index.ts
  src/SvgIcons/index.ts
  src/index.ts
Labels: enhancement

#601 Bugfix/summary card label delete button
  src/Card/SummaryCard/SummaryCard.tsx
  src/LabelSelector/LabelChip/LabelChip.js
  src/LabelSelector/LabelChip/LabelChip.stories.tsx
  src/LabelSelector/LabelChip/LabelChip.test.tsx
  src/LabelSelector/LabelChip/LabelChip.tsx
  src/LabelSelector/LabelChip/LabelChip.types.ts
  src/LabelSelector/LabelChip/index.js
  src/LabelSelector/LabelChip/index.ts
  src/LabelSelector/index.ts
  src/index.ts
Labels: bug

#585 renamed AppHeader to VirtoAppHeader
  src/AppHeader/index.ts
  src/AppLayout/AppLayout.tsx
  src/VirtoAppHeader/VirtoAppHeader.stories.tsx
  src/VirtoAppHeader/VirtoAppHeader.test.tsx
  src/VirtoAppHeader/VirtoAppHeader.tsx
  src/VirtoAppHeader/VirtoAppHeader.types.ts
  src/VirtoAppHeader/index.ts
  src/index.ts
Labels: enhancement

#606 Fix for file size restriction
  src/FileUploader/FileUploader.js
  src/FileUploader/FileUploader.stories.js
  src/ImageUploader/ImageUploader.js
Labels: bug

#607 Dep updates
  .storybook/main.js
  package-lock.json
  package.json
Labels: dependencies

#602 Feature/new app header
  src/AppHeader/AppHeader.stories.tsx
  src/AppHeader/AppHeader.test.tsx
  src/AppHeader/AppHeader.tsx
  src/AppHeader/AppHeader.types.ts
  src/AppHeader/index.ts
  src/index.ts
Labels: enhancement

#603 Feature/rename app layout to virto app layout
  src/AppLayout/index.js
  src/VirtoAppLayout/VirtoAppLayout.stories.tsx
  src/VirtoAppLayout/VirtoAppLayout.test.tsx
  src/VirtoAppLayout/VirtoAppLayout.tsx
  src/VirtoAppLayout/VirtoAppLayout.types.ts
  src/VirtoAppLayout/index.js
  src/index.ts
Labels: enhancement

#604 Feature/new app layout
  src/AppHeader/AppHeader.tsx
  src/AppLayout/AppLayout.stories.tsx
  src/AppLayout/AppLayout.test.tsx
  src/AppLayout/AppLayout.tsx
  src/AppLayout/AppLayout.types.ts
  src/AppLayout/index.ts
  src/Sidebar/SidebarItem/SidebarItem.tsx
  src/Sidebar/SidebarItem/SidebarItem.types.ts
  src/VirtoAppLayout/index.js
  src/VirtoAppLayout/index.ts
  src/index.ts
Labels: enhancement

#608 Bugfix/sidebar border
  src/Sidebar/SidebarItem/SidebarItem.stories.tsx
  src/Sidebar/SidebarItem/SidebarItem.tsx
Labels: bug
