Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-11, with the labels that each got.

#763 TD-2238 Changed exponent format to scientific notation for Line and surface Plots.
  src/LinePlot/LinePlot.tsx
  src/SurfacePlot/SurfacePlot.tsx
Labels: bug

#765 November Dependency Updates
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/Autocomplete/Autocomplete.stories.tsx
  src/LinePlot/LinePlot.stories.tsx
  src/RegistrationForm/RegistrationForm.test.js
  src/Select/Select.test.js
  src/SurfacePlot/SurfacePlot.stories.tsx
  src/VehicleSelect/VehicleSelect.stories.tsx
Labels: dependencies

#762 Enhancement - Options to allow key value array
  src/Autocomplete/Autocomplete.stories.tsx
  src/Autocomplete/Autocomplete.test.tsx
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
  src/Select/Select.jsx
Labels: enhancement

#766 Deploy js alongside ts
  .eslintignore
  .gitignore
  package-lock.json
  package.json
  src/Card/DetailCard/DetailCard.tsx
  src/Card/FileCard/FileCard.tsx
  src/Card/SummaryCard/SummaryCard.tsx
  tsconfig.json
Labels: enhancement

#769 Autocomplete Component - use isOptionEqualToValue method
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
  src/Common.types.ts
  src/LabelSelector/LabelSelector.jsx
  src/utils/common.ts
Labels: enhancement

#770 TD-2308 Add support to show helper icon and tooltip
  src/Autocomplete/Autocomplete.stories.tsx
  src/Autocomplete/Autocomplete.test.tsx
  src/Autocomplete/Autocomplete.tsx
  src/Common.types.ts
  src/utils/common.ts
Labels: enhancement

#771 Migrate ConfirmProvider, SnackbarProvider and UserAvatar to typescript
  src/ConfirmProvider/ConfirmProvider.stories.tsx
  src/ConfirmProvider/ConfirmProvider.test.tsx
  src/ConfirmProvider/ConfirmProvider.tsx
  src/ConfirmProvider/ConfirmProvider.types.ts
  src/ConfirmProvider/index.d.ts
  src/ConfirmProvider/index.js
  src/ConfirmProvider/index.ts
  src/SnackbarProvider/SnackbarContext.tsx
  src/SnackbarProvider/SnackbarProvider.tsx
  src/SnackbarProvider/SnackbarProvider.types.ts
  src/SnackbarProvider/index.d.ts
  src/SnackbarProvider/index.ts
  src/SnackbarProvider/useSnackbar.ts
  src/UserAvatar/UserAvatar.stories.tsx
  src/UserAvatar/UserAvatar.test.tsx
  src/UserAvatar/UserAvatar.tsx
  src/UserAvatar/UserAvatar.types.ts
  src/UserAvatar/colorMap.tsx
  src/UserAvatar/index.d.ts
  src/UserAvatar/index.tsx
Labels: enhancement
