Repository IPG-Automotive-UK/react-ui, pull requests merged in 2023-07, with the labels that each got.

#654 updated dependencies to latest versions
  package-lock.json
  package.json
Labels: dependencies

#655 Switch ActionDialog to typescript
  src/ActionDialog/ActionDialog.js
  src/ActionDialog/ActionDialog.stories.js
  src/ActionDialog/ActionDialog.stories.tsx
  src/ActionDialog/ActionDialog.test.tsx
  src/ActionDialog/ActionDialog.tsx
  src/ActionDialog/ActionDialog.types.ts
  src/ActionDialog/index.js
  src/ActionDialog/index.ts
  src/index.ts
Labels: enhancement

#662 Snackbar flex-wrap
  src/Snackbar/Snackbar.stories.tsx
  src/Snackbar/Snackbar.test.tsx
  src/Snackbar/Snackbar.tsx
  src/Snackbar/Snackbar.types.ts
  src/Snackbar/index.js
  src/Snackbar/index.ts
  src/index.ts
Labels: bug

#659 Migrate Wizard components to typescript
  src/Wizard/Wizard.stories.tsx
  src/Wizard/Wizard.test.tsx
  src/Wizard/Wizard.tsx
  src/Wizard/Wizard.types.ts
  src/Wizard/WizardActions/BackButton/BackButton.stories.js
  src/Wizard/WizardActions/BackButton/BackButton.stories.tsx
  src/Wizard/WizardActions/BackButton/BackButton.test.tsx
  src/Wizard/WizardActions/BackButton/BackButton.tsx
  src/Wizard/WizardActions/BackButton/index.ts
  src/Wizard/WizardActions/CancelButton/CancelButton.js
  src/Wizard/WizardActions/CancelButton/CancelButton.stories.js
  src/Wizard/WizardActions/CancelButton/CancelButton.stories.tsx
  src/Wizard/WizardActions/CancelButton/CancelButton.test.tsx
  src/Wizard/WizardActions/CancelButton/CancelButton.tsx
  src/Wizard/WizardActions/CancelButton/index.ts
  src/Wizard/WizardActions/NextButton/NextButton.stories.js
  src/Wizard/WizardActions/NextButton/NextButton.stories.tsx
  src/Wizard/WizardActions/NextButton/NextButton.test.tsx
  src/Wizard/WizardActions/NextButton/NextButton.tsx
  src/Wizard/WizardActions/NextButton/index.ts
  src/Wizard/WizardActions/WizardActions.stories.tsx
  src/Wizard/WizardActions/WizardActions.test.tsx
  src/Wizard/WizardActions/WizardActions.tsx
  src/Wizard/WizardActions/WizardActions.types.ts
  src/Wizard/WizardActions/WizardButton.types.ts
  src/Wizard/WizardActions/index.ts
  src/Wizard/WizardContent/WizardContent.stories.tsx
  src/Wizard/WizardContent/WizardContent.test.tsx
  src/Wizard/WizardContent/WizardContent.tsx
  src/Wizard/WizardContent/WizardContent.types.ts
  src/Wizard/WizardContent/index.js
  src/Wizard/WizardContent/index.ts
  src/Wizard/WizardSteps/WizardStep/WizardStep.stories.tsx
  src/Wizard/WizardSteps/WizardStep/WizardStep.test.tsx
  src/Wizard/WizardSteps/WizardStep/WizardStep.tsx
  src/Wizard/WizardSteps/WizardStep/WizardStep.types.ts
  src/Wizard/WizardSteps/WizardStep/index.js
  src/Wizard/WizardSteps/WizardStep/index.ts
  src/Wizard/WizardSteps/WizardSteps.stories.tsx
  src/Wizard/WizardSteps/WizardSteps.test.tsx
  src/Wizard/WizardSteps/WizardSteps.tsx
  src/Wizard/WizardSteps/WizardSteps.types.ts
  src/Wizard/WizardSteps/index.js
  src/Wizard/WizardSteps/index.ts
  src/Wizard/index.js
  src/Wizard/index.ts
  src/index.ts
Labels: enhancement

#657 Improve AppHeader / AppLayout stories
  .storybook/decorators.tsx
  src/AppHeader/AppHeader.stories.tsx
  src/AppLayout/AppLayout.stories.tsx
  src/UserMenu/UserMenu.stories.tsx
  src/VirtoAppHeader/VirtoAppHeader.stories.tsx
  src/VirtoAppLayout/VirtoAppLayout.stories.tsx
Labels: bug
