Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-01, with the labels that each got.

#804 January Dependencies Update
  package-lock.json
  package.json
Labels: dependencies

#803 TD-1300 Label Chip in Detail Card
  src/Card/DetailCard/DetailCard.test.tsx
  src/Card/DetailCard/DetailCard.tsx
Labels: bug

#802 TD-1555 Remove mui-file-dropzone & @mui/styles dependencies
  package-lock.json
  package.json
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.test.tsx
  src/FileUploader/FileUploader.tsx
  src/FileUploader/FileUploader.types.ts
  src/ImageUploader/ImageUploader.stories.tsx
  src/ImageUploader/ImageUploader.test.tsx
  src/ImageUploader/ImageUploader.tsx
  src/ImageUploader/ImageUploader.types.tsx
  src/Uploader/Uploader.types.ts
  src/Uploader/UploaderHeader.tsx
  src/Uploader/UploaderHeader.types.ts
  src/Uploader/useUploader.ts
  src/Uploader/useUploader.types.ts
  src/utils/readAsDataURL.ts
Labels: enhancement, dependencies

#805 TD-1555 Replace peerDependencies with dependencies
  package-lock.json
  package.json
Labels: dependencies

#807 TD-2438 file picker validation state
  package-lock.json
  package.json
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.test.tsx
  src/FileUploader/FileUploader.tsx
  src/FileUploader/FileUploader.types.ts
Labels: enhancement

#806 TreeViewList Component
  package-lock.json
  package.json
  src/TreeViewList/TreeViewList.spec.tsx
  src/TreeViewList/TreeViewList.stories.tsx
  src/TreeViewList/TreeViewList.tsx
  src/TreeViewList/TreeViewList.types.ts
  src/TreeViewList/index.ts
Labels: enhancement

#808 TreeViewList - expand search items
  src/TreeViewList/TreeViewList.spec.tsx
  src/TreeViewList/TreeViewList.stories.tsx
  src/TreeViewList/TreeViewList.tsx
  src/TreeViewList/TreeViewList.types.ts
Labels: enhancement
