Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-05, with the labels that each got.

#859 Deprecate string[] syntax for acceptedFiles
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.tsx
  src/FileUploader/FileUploader.types.ts
  src/Uploader/useUploader.ts
Labels: enhancement

#858 Release/v7.6.0
  package.json
  pnpm-lock.yaml
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
  src/PartSelector/PartSelector.spec.ts
  src/PartSelector/PartSelector.stories.tsx
  src/PartSelector/PartSelector.tsx
  src/PartSelector/PartSelector.types.ts
  src/PartSelector/index.ts
  src/TabPanel/TabPanel.spec.tsx
  src/TabPanel/TabPanel.stories.tsx
  src/TabPanel/TabPanel.tsx
  src/TabPanel/TabPanel.types.ts
  src/ThemeProvider/ThemeProvider.test.tsx
  src/VehicleSelector/VehicleSelector.stories.tsx
  src/VehicleSelector/VehicleSelector.tsx
  src/VehicleSelector/VehicleSelector.types.ts
  src/index.ts
  src/utils/common.ts
Labels: enhancement

#863 DataGrid styling with ThemeProvider
  package.json
  pnpm-lock.yaml
  src/ThemeProvider/ThemeProvider.stories.tsx
  src/ThemeProvider/ThemeProvider.tsx
Labels: bug

#867 File uploader title and delete icon alignment
  src/Uploader/UploaderHeader.tsx
Labels: enhancement

#850 TD-2675 Create roadview vehicle path component
  src/VehiclePath/Marker.tsx
  src/VehiclePath/Vehicle.tsx
  src/VehiclePath/VehiclePath.spec.tsx
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/colored-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/colored-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/colored-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/coloredMarker-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/coloredMarker-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/coloredMarker-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/coloredVehicle-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/coloredVehicle-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/coloredVehicle-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/default-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/default-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/default-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/hiddenPath-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/hiddenPath-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/hiddenPath-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/labeledVehicle-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/labeledVehicle-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/labeledVehicle-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/strokeWidth-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/strokeWidth-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/strokeWidth-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withMarker-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withMarker-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withMarker-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withVehicle-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withVehicle-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withVehicle-webkit-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withYawedVehicle-chromium-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withYawedVehicle-firefox-linux.png
  src/VehiclePath/VehiclePath.spec.tsx-snapshots/withYawedVehicle-webkit-linux.png
  src/VehiclePath/VehiclePath.stories.tsx
  src/VehiclePath/VehiclePath.tsx
  src/VehiclePath/VehiclePath.types.tsx
  src/VehiclePath/index.ts
  src/index.ts
Labels: enhancement

#849 TD-2675 Create roadview road components
  src/RoadMarking/RoadMarking.spec.tsx
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/colored-chromium-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/colored-firefox-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/colored-webkit-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/dashed-chromium-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/dashed-firefox-linux .png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/dashed-webkit-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/default-chromium-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/default-firefox-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/default-webkit-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/double-chromium-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/double-firefox-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/double-webkit-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/positioned-chromium-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/positioned-firefox-linux.png
  src/RoadMarking/RoadMarking.spec.tsx-snapshots/positioned-webkit-linux.png
  src/RoadMarking/RoadMarking.stories.tsx
  src/RoadMarking/RoadMarking.tsx
  src/RoadMarking/RoadMarking.types.tsx
  src/RoadMarking/index.ts
  src/RoadSurface/RoadSurface.spec.tsx
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/colored-chromium-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/colored-firefox-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/colored-webkit-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/default-chromium-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/default-firefox-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/default-webkit-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/repositioned-chromium-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/repositioned-firefox-linux.png
  src/RoadSurface/RoadSurface.spec.tsx-snapshots/repositioned-webkit-linux.png
  src/RoadSurface/RoadSurface.stories.tsx
  src/RoadSurface/RoadSurface.tsx
  src/RoadSurface/RoadSurface.types.ts
  src/RoadSurface/index.ts
  src/index.ts
Labels: enhancement

#847 TD-2675 Create traffic light component
  src/TrafficLight/TrafficLight.spec.tsx
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/default-chromium-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/default-firefox-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/default-webkit-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/green-chromium-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/green-firefox-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/green-webkit-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/positioned-chromium-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/positioned-firefox-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/positioned-webkit-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/rotated-chromium-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/rotated-firefox-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/rotated-webkit-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/scaled-chromium-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/scaled-firefox-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/scaled-webkit-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/type-chromium-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/type-firefox-linux.png
  src/TrafficLight/TrafficLight.spec.tsx-snapshots/type-webkit-linux.png
  src/TrafficLight/TrafficLight.stories.tsx
  src/TrafficLight/TrafficLight.tsx
  src/TrafficLight/TrafficLight.types.ts
  src/TrafficLight/TrafficLightSelector.tsx
  src/TrafficLight/TrafficLightSelector.types.ts
  src/TrafficLight/index.ts
  src/TrafficLight/svg/arrow-left-green.svg
  src/TrafficLight/svg/arrow-left.svg
  src/TrafficLight/svg/arrow-right-green.svg
  src/TrafficLight/svg/arrow-right.svg
  src/TrafficLight/svg/arrow-up-green.svg
  src/TrafficLight/svg/arrow-up.svg
  src/TrafficLight/svg/arrows-up-left-green.svg
  src/TrafficLight/svg/arrows-up-left.svg
  src/TrafficLight/svg/arrows-up-right-green.svg
  src/TrafficLight/svg/arrows-up-right.svg
  src/TrafficLight/svg/hand-stop.svg
  src/TrafficLight/svg/walk.svg
  src/TrafficLight/trafficLightUtils.ts
  src/index.ts
Labels: enhancement

#866 Storybook 8
  .storybook/main.ts
  package.json
  pnpm-lock.yaml
Labels: dependencies

#869 TD 2737 Create React UI Bullet Gauge component
  src/BulletGauge/BulletGauge.spec.tsx
  src/BulletGauge/BulletGauge.stories.tsx
  src/BulletGauge/BulletGauge.tsx
  src/BulletGauge/BulletGauge.types.ts
  src/BulletGauge/BulletGaugeClientOnly.tsx
  src/BulletGauge/index.ts
  src/LinePlot/LinePlot.types.ts
  src/SurfacePlot/SurfacePlot.types.ts
  src/index.ts
  src/utils/common.ts
Labels: enhancement

#870 Fix ImageUploader container's wrong spelled CSS property
  src/ImageUploader/ImageUploader.tsx
Labels: bug

#873 TD-2770 ImageUploader loading state
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.test.tsx
  src/FileUploader/FileUploader.tsx
  src/ImageUploader/ImageUploader.stories.tsx
  src/ImageUploader/ImageUploader.test.tsx
  src/ImageUploader/ImageUploader.tsx
  src/ImageUploader/ImageUploader.types.tsx
  src/Uploader/useUploader.ts
Labels: enhancement

#876 TrafficLight type fix
  src/TrafficSign/TrafficSign.types.ts
Labels: bug

#879 TD-2782 Forces version of material-ui-confirm to 3.0.12
  package.json
  pnpm-lock.yaml
Labels: enhancement
