Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-07, with the labels that each got.

#899 Bug - TD-2849 Fix Breadcrumb and Numberfield visual defect
  src/Breadcrumbs/Breadcrumbs.stories.tsx
  src/Breadcrumbs/Breadcrumbs.tsx
  src/NumberField/NumberField.tsx
Labels: bug

#900 Fix TabPanel overflow behaviour
  src/TabPanel/TabPanel.stories.tsx
  src/TabPanel/TabPanel.tsx
  src/TabPanel/TabPanel.types.ts
Labels: bug

#901 Bug - VE-75 NumberField label overlap
  src/NumberField/NumberField.tsx
Labels: bug

#902 Fix TabPanel exceeding parent size
  src/TabPanel/TabPanel.tsx
Labels: bug

#903 Fix TabPanel Styling
  src/TabPanel/TabPanel.tsx
Labels: bug

#906 Merge main release into v8.0.0
  .vscode/launch.json
  package-lock.json
  src/Card/DetailCard/DetailCard.stories.tsx
  src/Card/DetailCard/DetailCard.test.tsx
  src/Card/DetailCard/DetailCard.tsx
  src/Card/DetailCard/DetailCard.types.ts
  src/Card/DetailCard/index.ts
  src/Card/SummaryCard/SummaryCard.test.tsx
  src/Card/SummaryCard/SummaryCard.tsx
  src/Card/index.ts
  src/LabelSelector/LabelChip/LabelChip.test.tsx
  src/LabelSelector/LabelChip/LabelChip.tsx
  src/LabelSelector/LabelChip/LabelChip.types.ts
  src/LabelSelector/LabelChipGroup/LabelChipGroup.spec.tsx
  src/LabelSelector/LabelChipGroup/LabelChipGroup.stories.tsx
  src/LabelSelector/LabelChipGroup/LabelChipGroup.tsx
  src/LabelSelector/LabelChipGroup/LabelChipGroup.types.ts
  src/LabelSelector/LabelChipGroup/index.ts
  src/LabelSelector/index.ts
  src/index.ts
Labels: help wanted

#907 Add inputValue prop to Autocomplete
  src/Autocomplete/Autocomplete.stories.tsx
  src/Autocomplete/Autocomplete.test.tsx
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
Labels: enhancement

#860 Release/v8.0.0
  Dockerfile
  package-lock.json
  package.json
  pnpm-lock.yaml
  pre-release.md
  src/Autocomplete/Autocomplete.stories.tsx
  src/Autocomplete/Autocomplete.test.tsx
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
  src/Breadcrumbs/Breadcrumbs.stories.tsx
  src/Breadcrumbs/Breadcrumbs.tsx
  src/Card/DetailCard/DetailCard.test.tsx
  src/Card/DetailCard/DetailCard.tsx
  src/Card/DetailCard/DetailCard.types.ts
  src/Card/FileCard/FileCard.tsx
  src/Card/FileCard/index.ts
  src/Card/SummaryCard/SummaryCard.stories.tsx
  src/Card/SummaryCard/SummaryCard.test.tsx
  src/Card/SummaryCard/SummaryCard.tsx
  src/Card/SummaryCard/SummaryCard.types.ts
  src/Card/index.ts
  src/CardContent/FileDetails/FileDetails.stories.tsx
  src/CardContent/FileDetails/FileDetails.test.tsx
  src/CardContent/FileDetails/FileDetails.tsx
  src/CardContent/FileDetails/FileDetails.types.ts
  src/CardContent/FileDetails/index.ts
  src/CardContent/Infographic/Infographic.stories.tsx
  src/CardContent/Infographic/Infographic.test.tsx
  src/CardContent/Infographic/Infographic.tsx
  src/CardContent/Infographic/Infographic.types.ts
  src/CardContent/Infographic/index.ts
  src/CardContent/index.ts
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.test.tsx
  src/FileUploader/FileUploader.tsx
  src/FileUploader/FileUploader.types.ts
  src/NumberField/NumberField.jsx
  src/NumberField/NumberField.stories.tsx
  src/NumberField/NumberField.test.jsx
  src/NumberField/NumberField.test.tsx
  src/NumberField/NumberField.tsx
  src/NumberField/NumberField.types.ts
  src/NumberField/index.ts
  src/TabPanel/TabPanel.stories.tsx
  src/TabPanel/TabPanel.tsx
  src/TabPanel/TabPanel.types.ts
  src/Uploader/useUploader.ts
  src/VersionChip/VersionChip.stories.tsx
  src/VersionChip/VersionChip.test.tsx
  src/VersionChip/VersionChip.tsx
  src/VersionChip/VersionChip.types.tsx
  src/Wizard/WizardSteps/WizardStep/WizardStep.stories.tsx
  src/Wizard/WizardSteps/WizardStep/WizardStep.test.tsx
  src/Wizard/WizardSteps/WizardStep/WizardStep.tsx
  src/Wizard/WizardSteps/WizardStep/WizardStep.types.ts
  src/Wizard/WizardSteps/WizardSteps.stories.tsx
  src/index.ts
Labels: enhancement, dependencies

#908 Remove mistaken package-lock and add to gitignore
  .gitignore
  package-lock.json
Labels: invalid

#911 Enhancement - Add href support to FileDetails download button
  src/CardContent/FileDetails/FileDetails.stories.tsx
  src/CardContent/FileDetails/FileDetails.test.tsx
  src/CardContent/FileDetails/FileDetails.tsx
  src/CardContent/FileDetails/FileDetails.types.ts
Labels: enhancement

#909 VE-84 plot styling fixes
  package.json
  src/LinePlot/LinePlot.stories.tsx
  src/LinePlot/LinePlot.tsx
  src/LinePlot/LinePlot.types.ts
  src/SurfacePlot/SurfacePlot.stories.tsx
  src/SurfacePlot/SurfacePlot.tsx
  src/SurfacePlot/SurfacePlot.types.ts
Labels: bug

#910 Release/v8.1.0
  package.json
  src/CardContent/FileDetails/FileDetails.stories.tsx
  src/CardContent/FileDetails/FileDetails.test.tsx
  src/CardContent/FileDetails/FileDetails.tsx
  src/CardContent/FileDetails/FileDetails.types.ts
  src/LinePlot/LinePlot.stories.tsx
  src/LinePlot/LinePlot.tsx
  src/LinePlot/LinePlot.types.ts
  src/SurfacePlot/SurfacePlot.stories.tsx
  src/SurfacePlot/SurfacePlot.tsx
  src/SurfacePlot/SurfacePlot.types.ts
Labels: enhancement

#913 Update Dockerfile to use a standardised version of pnpm
  Dockerfile
  package.json
Labels: dependencies

#914 VE-69 July dependency updates
  .storybook/DocsContainer.tsx
  .storybook/decorators.tsx
  .storybook/preview.tsx
  Dockerfile
  package.json
  pnpm-lock.yaml
  src/Autocomplete/Autocomplete.test.tsx
  src/LabelSelector/LabelSelector.test.jsx
  src/VehiclePath/VehiclePath.tsx
  src/VersionChip/VersionChip.tsx
  vitest.config.mts
Labels: dependencies

#912 TD-2886: Tab panel background now fills whole panel
  package.json
  src/TabPanel/TabPanel.stories.tsx
  src/TabPanel/TabPanel.tsx
Labels: bug

#918 TD -2915 Update wizard title prop to support element
  src/Wizard/Wizard.stories.tsx
  src/Wizard/Wizard.test.tsx
  src/Wizard/Wizard.tsx
  src/Wizard/Wizard.types.ts
  src/Wizard/WizardSteps/WizardSteps.stories.tsx
Labels: enhancement

#915 add dark mode styling for preview and loading containers
  .storybook/main.ts
  .storybook/preview.tsx
  .storybook/styles.css
  package.json
  pnpm-lock.yaml
Labels: bug
