Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-04, with the labels that each got.

#840 April Dependency Update
  package.json
  pnpm-lock.yaml
  src/MultiColor/MultiColor.test.jsx
Labels: dependencies

#841 TD-2594 Create React UI - Variant vehicle search component
  src/VehicleSelector/VehicleSelector.spec.tsx
  src/VehicleSelector/VehicleSelector.stories.tsx
  src/VehicleSelector/VehicleSelector.tsx
  src/VehicleSelector/VehicleSelector.types.ts
  src/VehicleSelector/index.ts
Labels: enhancement

#843 TD-2652 TreeViewList component - improvements and bugs
  package.json
  src/TabPanel/TabPanel.tsx
  src/TreeViewList/TreeViewList.spec.tsx
  src/TreeViewList/TreeViewList.tsx
  src/TreeViewList/example-items.json
  src/index.ts
Labels: bug, enhancement

#844 TD 2659 Update NumberField and FileUploaders
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.types.ts
  src/ImageUploader/ImageUploader.stories.tsx
  src/ImageUploader/ImageUploader.types.tsx
  src/NumberField/NumberField.jsx
  src/NumberField/NumberField.stories.jsx
  src/NumberField/NumberField.test.jsx
  src/Uploader/Uploader.types.ts
  src/Uploader/useUploader.ts
  src/Uploader/useUploader.types.ts
Labels: enhancement

#845 TD 2659 - Updates to wizard and file uploader
  src/FileUploader/FileUploader.stories.tsx
  src/FileUploader/FileUploader.test.tsx
  src/FileUploader/FileUploader.tsx
  src/FileUploader/FileUploader.types.ts
  src/Wizard/WizardSteps/WizardSteps.tsx
Labels: enhancement

#846 Create figure component
  .dockerignore
  .github/workflows/test.yml
  .gitignore
  Dockerfile
  compose.yml
  package-lock.json
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/Figure/Figure.spec.tsx
  src/Figure/Figure.spec.tsx-snapshots/default-chromium-linux.png
  src/Figure/Figure.spec.tsx-snapshots/default-firefox-linux.png
  src/Figure/Figure.spec.tsx-snapshots/default-webkit-linux.png
  src/Figure/Figure.spec.tsx-snapshots/positioned-chromium-linux.png
  src/Figure/Figure.spec.tsx-snapshots/positioned-firefox-linux.png
  src/Figure/Figure.spec.tsx-snapshots/positioned-webkit-linux.png
  src/Figure/Figure.spec.tsx-snapshots/rotated-chromium-linux.png
  src/Figure/Figure.spec.tsx-snapshots/rotated-firefox-linux.png
  src/Figure/Figure.spec.tsx-snapshots/rotated-webkit-linux.png
  src/Figure/Figure.spec.tsx-snapshots/scaled-chromium-linux.png
  src/Figure/Figure.spec.tsx-snapshots/scaled-firefox-linux.png
  src/Figure/Figure.spec.tsx-snapshots/scaled-webkit-linux.png
  src/Figure/Figure.spec.tsx-snapshots/sized-chromium-linux.png
  src/Figure/Figure.spec.tsx-snapshots/sized-firefox-linux.png
  src/Figure/Figure.spec.tsx-snapshots/sized-webkit-linux.png
  src/Figure/Figure.stories.tsx
  src/Figure/Figure.tsx
  src/Figure/Figure.types.ts
  src/Figure/figureExampleSvg.svg
  src/Figure/index.ts
  vitest.config.ts
Labels: enhancement

#852 TD-2716 TabPanel - Add functionality to allow custom button in tab
  src/TabPanel/TabPanel.spec.tsx
  src/TabPanel/TabPanel.stories.tsx
  src/TabPanel/TabPanel.tsx
  src/TabPanel/TabPanel.types.ts
Labels: enhancement

#851 TD-2691 Create React UI Part Selector Component
  package.json
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
  src/PartSelector/PartSelector.spec.ts
  src/PartSelector/PartSelector.stories.tsx
  src/PartSelector/PartSelector.tsx
  src/PartSelector/PartSelector.types.ts
  src/PartSelector/index.ts
  src/VehicleSelector/VehicleSelector.stories.tsx
  src/VehicleSelector/VehicleSelector.tsx
  src/VehicleSelector/VehicleSelector.types.ts
  src/index.ts
  src/utils/common.ts
Labels: enhancement
