Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-02, with the labels that each got.

#813 TD-2453 Update available statuses
  src/Status/StatusCard/StatusCard.stories.tsx
  src/Status/StatusCard/StatusCard.types.ts
  src/Status/StatusIcon/StatusIcon.types.ts
  src/Status/StatusLabel/StatusLabel.types.ts
  src/Status/statuses.ts
  src/Status/statuses.types.ts
Labels: enhancement

#814 Remove extra bottom padding and border from TableCard component
  src/Card/TableCard/TableCard.jsx
Labels: bug

#809 TreeViewList searching bug and simplified interface
  src/TreeViewList/TreeViewList.spec.tsx
  src/TreeViewList/TreeViewList.stories.tsx
  src/TreeViewList/TreeViewList.tsx
  src/TreeViewList/TreeViewList.types.ts
  src/TreeViewList/example-items.json
Labels: bug, enhancement

#816 Remove type=module
  package-lock.json
  package.json
  serve-storybook.js
Labels: bug

#817 Show tooltip only if text overflows
  src/NoWrapTypography/NoWrapTypography.spec.tsx
  src/NoWrapTypography/NoWrapTypography.stories.tsx
  src/NoWrapTypography/NoWrapTypography.test.tsx
  src/NoWrapTypography/NoWrapTypography.tsx
Labels: bug

#818 NoWrapTypography sx prop does not work
  package.json
  playwright.config.ts
  src/NoWrapTypography/NoWrapTypography.stories.tsx
  src/NoWrapTypography/NoWrapTypography.test.tsx
  src/NoWrapTypography/NoWrapTypography.tsx
Labels: bug

#815 Enhancement - TreeViewList improvements
  src/TreeViewList/TreeViewList.spec.tsx
  src/TreeViewList/TreeViewList.stories.tsx
  src/TreeViewList/TreeViewList.tsx
  src/TreeViewList/TreeViewList.types.ts
  src/TreeViewList/example-items.json
Labels: enhancement

#820 Update LoadErrorMessage components
  package-lock.json
  package.json
  src/LoadErrorMessage/LoadErrorMessage.spec.tsx
  src/LoadErrorMessage/LoadErrorMessage.stories.tsx
  src/LoadErrorMessage/LoadErrorMessage.tsx
  src/LoadErrorMessage/LoadErrorMessage.types.ts
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/VirtoHeadScratching.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/VirtoHeadScratching.tsx
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/VirtoHeadScratching.types.ts
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/index.ts
  src/SvgIcons/VirtoMascots/VirtoShrugging/VirtoShrugging.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoShrugging/VirtoShrugging.tsx
  src/SvgIcons/VirtoMascots/VirtoShrugging/VirtoShrugging.types.ts
  src/SvgIcons/VirtoMascots/VirtoShrugging/index.ts
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.tsx
  src/SvgIcons/index.ts
Labels: enhancement

#822 Fix default contactUrl for errors in LoadErrorMessage
  src/LoadErrorMessage/LoadErrorMessage.tsx
Labels: bug
