Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-03, with the labels that each got.

#823 Default to not showing a button on LoadErrorMessage 404
  src/LoadErrorMessage/LoadErrorMessage.tsx
Labels: bug

#826 TD-1854 Open current app link in the current tab
  package-lock.json
  package.json
  src/AppLauncher/AppLauncher.tsx
Labels: enhancement

#824 Enhancement - TreeViewList improvements
  src/SearchBar/SearchBar.tsx
  src/SearchBar/SearchBar.types.ts
  src/TreeViewList/TreeViewList.stories.tsx
  src/TreeViewList/TreeViewList.tsx
  src/TreeViewList/TreeViewList.types.ts
Labels: bug, enhancement

#825 March Dependency Update
  package-lock.json
  package.json
Labels: dependencies

#811 Future/pnpm
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies

#830 TreeViewList - Improved performance
  src/TreeViewList/TreeViewList.tsx
Labels: enhancement

#833 TreeViewList - No search results message implementation
  src/TreeViewList/TreeViewList.spec.tsx
  src/TreeViewList/TreeViewList.tsx
Labels: enhancement

#832 TD-2555 - Wizard title margin reduced
  src/Wizard/Wizard.tsx
Labels: bug

#834 Create a Selector Button
  src/SelectorButton/SelectorButton.stories.tsx
  src/SelectorButton/SelectorButton.test.tsx
  src/SelectorButton/SelectorButton.tsx
  src/SelectorButton/index.ts
  src/index.ts
Labels: enhancement

#836 Description field made optional on SelectorButton
  src/SelectorButton/index.ts
Labels: enhancement

#838 Add updated boxShadow to Selector Component
  src/SelectorButton/SelectorButton.tsx
Labels: enhancement

#837 TD-2593 - Create React UI Tabbed Panel component
  src/TabPanel/TabPanel.spec.tsx
  src/TabPanel/TabPanel.stories.tsx
  src/TabPanel/TabPanel.tsx
  src/TabPanel/TabPanel.types.ts
  src/TabPanel/index.ts
  src/TreeViewList/TreeViewList.tsx
  src/index.ts
Labels: enhancement

#835 Uncontrolled input component updates
  package.json
  src/Autocomplete/Autocomplete.stories.tsx
  src/Autocomplete/Autocomplete.test.tsx
  src/Autocomplete/Autocomplete.tsx
  src/Autocomplete/Autocomplete.types.ts
  src/Checkbox/Checkbox.jsx
  src/Checkbox/Checkbox.stories.jsx
  src/Checkbox/Checkbox.test.jsx
  src/Checkbox/index.ts
  src/LabelSelector/LabelSelector.d.ts
  src/LabelSelector/LabelSelector.jsx
  src/LabelSelector/LabelSelector.stories.jsx
  src/LabelSelector/LabelSelector.test.jsx
  src/NumberField/NumberField.jsx
  src/NumberField/NumberField.stories.jsx
  src/NumberField/NumberField.test.jsx
  src/NumberField/index.ts
  src/RadioButtons/RadioButtons.jsx
  src/RadioButtons/RadioButtons.stories.jsx
  src/RadioButtons/RadioButtons.test.jsx
  src/RadioButtons/index.ts
  src/SwitchField/SwitchField.jsx
  src/SwitchField/SwitchField.stories.jsx
  src/SwitchField/SwitchField.test.jsx
  src/SwitchField/index.ts
  src/TextField/TextField.stories.tsx
  src/TextField/TextField.test.tsx
  src/TextField/TextField.tsx
  src/TextField/TextField.types.ts
Labels: enhancement
