Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-06, with the labels that each got.

#885 VE- 49 React UI updates for x tree view and vi test imports
  package.json
  pnpm-lock.yaml
  src/ActionDialog/ActionDialog.test.tsx
  src/Autocomplete/Autocomplete.test.tsx
  src/ImageUploader/ImageUploader.test.tsx
  src/TreeViewList/TreeViewList.tsx
Labels: bug, dependencies

#886 Release/v7.8.3
  package.json
  pnpm-lock.yaml
  src/ActionDialog/ActionDialog.test.tsx
  src/Autocomplete/Autocomplete.test.tsx
  src/ImageUploader/ImageUploader.test.tsx
  src/TreeViewList/TreeViewList.tsx
  src/TreeViewList/TreeViewList.types.ts
Labels: bug, dependencies

#884 VE-47 React UI component improvements
  src/LinePlot/LinePlot.stories.tsx
  src/LinePlot/LinePlot.tsx
  src/LinePlot/LinePlot.types.ts
  src/LinePlot/LinePlotClientOnly.tsx
  src/SurfacePlot/SurfacePlot.stories.tsx
  src/SurfacePlot/SurfacePlot.tsx
  src/SurfacePlot/SurfacePlot.types.ts
  src/TabPanel/TabPanel.tsx
  src/TreeViewList/TreeViewList.tsx
Labels: bug, enhancement

#890 Enhancement - Red asterisk
  src/ThemeProvider/ThemeProvider.tsx
Labels: enhancement

#892 VE-64 TreeViewList add tree connector line
  src/TreeViewList/TreeViewList.tsx
Labels: enhancement

#897 Remove playwright install from Dockerfile
  Dockerfile
Labels: bug

#894 Bugfix - Fix console error from spreading key prop
  src/Autocomplete/Autocomplete.tsx
Labels: bug

#896 TD-2815 update card summary component
  src/Card/SummaryCard/SummaryCard.stories.tsx
  src/Card/SummaryCard/SummaryCard.test.tsx
  src/Card/SummaryCard/SummaryCard.tsx
  src/Card/SummaryCard/SummaryCard.types.ts
  src/CardContent/Infographic/Infographic.tsx
Labels: enhancement

#898 Add deploy-previews and persistent deployment using Chromatic
  .github/workflows/chromatic.yml
  .gitignore
  README.md
  package.json
  pnpm-lock.yaml
  src/Card/DetailCard/DetailCard.stories.tsx
  src/Card/DetailCard/DetailCard.test.tsx
  src/Card/SummaryCard/SummaryCard.stories.tsx
Labels: enhancement
