Repository IPG-Automotive-UK/react-ui, pull requests merged in 2024-09, with the labels that each got.

#933 TD-3048 Update RUI TruncatedTooltip component to enable showing tooltip when element not truncated
  src/TruncatedTooltip/TruncatedTooltip.spec.tsx
  src/TruncatedTooltip/TruncatedTooltip.stories.tsx
  src/TruncatedTooltip/TruncatedTooltip.tsx
  src/TruncatedTooltip/TruncatedTooltip.types.ts
Labels: enhancement

#937 TD-3050 - Fix the close button alignment
  src/DialogTitle/DialogTitle.tsx
Labels: bug

#935 TD-2804-Cannot-build-CRA-based-apps-with-latest-RUI
  package.json
  pnpm-lock.yaml
  src/index.ts
Labels: bug, good first issue

#938 TD-2804-Comment-out-Figure-component-to-resolve-react-konva-build-issue
  src/index.ts
Labels: bug

#940 TD-3036 - VirtoThumbsUpLeft
  src/LoadErrorMessage/LoadErrorMessage.tsx
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/VirtoHeadScratching.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/VirtoHeadScratching.tsx
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/index.ts
  src/SvgIcons/VirtoMascots/VirtoShrugging/VirtoShrugging.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoShrugging/VirtoShrugging.tsx
  src/SvgIcons/VirtoMascots/VirtoShrugging/index.ts
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.tsx
  src/SvgIcons/VirtoMascots/VirtoThinking/index.ts
  src/SvgIcons/VirtoMascots/VirtoThumbsUpLeft/VirtoThumbsUpLeft.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoThumbsUpLeft/VirtoThumbsUpLeft.tsx
  src/SvgIcons/VirtoMascots/VirtoThumbsUpLeft/VirtoThumbsUpLeft.types.ts
  src/SvgIcons/VirtoMascots/VirtoThumbsUpLeft/index.ts
  src/SvgIcons/index.ts
  src/index.ts
Labels: enhancement

#942 TD-3038 Update app launcher
  src/AppLauncher/AppLauncher.tsx
  src/VirtoAppHeader/VirtoAppHeader.tsx
Labels: enhancement

#941 TD - 3037 Update status card
  src/Status/StatusCard/StatusCard.stories.tsx
  src/Status/StatusCard/StatusCard.tsx
  src/Status/StatusCard/StatusCard.types.ts
  src/Status/StatusIcon/StatusIcon.stories.tsx
  src/Status/StatusIcon/StatusIcon.test.tsx
  src/Status/StatusIcon/StatusIcon.tsx
  src/Status/StatusIcon/StatusIcon.types.ts
  src/Status/statuses.ts
Labels: enhancement

#944 TD-3036 Export icon and replace svg
  src/Status/StatusCard/StatusCard.tsx
  src/SvgIcons/VirtoMascots/VirtoThumbsUpLeft/VirtoThumbsUpLeft.tsx
  src/index.ts
Labels: enhancement

#943 TD-3034 Road Preview Component
  package.json
  pnpm-lock.yaml
  src/DialogTitle/DialogTitle.tsx
  src/RoadPreview/RoadPreview.stories.tsx
  src/RoadPreview/RoadPreview.test.tsx
  src/RoadPreview/RoadPreview.tsx
  src/RoadPreview/RoadPreview.types.ts
  src/RoadPreview/index.ts
  src/index.ts
  static/asam.png
  static/carMaker.svg
Labels: enhancement

#945 bug/TD-3034-svg-icons-fix
  src/RoadPreview/RoadPreview.stories.tsx
  src/RoadPreview/RoadPreview.test.tsx
  src/RoadPreview/RoadPreview.tsx
  src/SvgIcons/AsamLogo/AsamLogo.stories.tsx
  src/SvgIcons/AsamLogo/AsamLogo.tsx
  src/SvgIcons/AsamLogo/AsamLogo.types.ts
  src/SvgIcons/AsamLogo/index.ts
  src/SvgIcons/CarMakerLogo/CarMakerLogo.stories.tsx
  src/SvgIcons/CarMakerLogo/CarMakerLogo.tsx
  src/SvgIcons/CarMakerLogo/CarMakerLogo.types.ts
  src/SvgIcons/CarMakerLogo/index.ts
  src/SvgIcons/index.ts
  src/index.ts
  static/asam.png
  static/carMaker.svg
Labels: bug

#946 TD-3034 Added Optional SX Props
  src/RoadPreview/RoadPreview.stories.tsx
  src/RoadPreview/RoadPreview.tsx
  src/RoadPreview/RoadPreview.types.ts
Labels: bug

#947 TD-3036 VIRTO Robot SVG resolution
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/VirtoHeadScratching.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoHeadScratching/VirtoHeadScratching.tsx
  src/SvgIcons/VirtoMascots/VirtoShrugging/VirtoShrugging.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoShrugging/VirtoShrugging.tsx
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoThinking/VirtoThinking.tsx
  src/SvgIcons/VirtoMascots/VirtoThumbsUpLeft/VirtoThumbsUpLeft.stories.tsx
  src/SvgIcons/VirtoMascots/VirtoThumbsUpLeft/VirtoThumbsUpLeft.tsx
Labels: bug

#948 VE-130/add-tabpanel-class-selector
  src/TabPanel/TabPanel.tsx
Labels: enhancement

#949 TD-3039 Add titleVariant prop
  src/Status/StatusCard/StatusCard.stories.tsx
  src/Status/StatusCard/StatusCard.test.tsx
  src/Status/StatusCard/StatusCard.tsx
  src/Status/StatusCard/StatusCard.types.ts
Labels: enhancement

#951 TD-3034 Remove redundant properties from RoadPreview types
  src/RoadPreview/RoadPreview.stories.tsx
  src/RoadPreview/RoadPreview.test.tsx
  src/RoadPreview/RoadPreview.tsx
  src/RoadPreview/RoadPreview.types.ts
Labels: bug

#954 TD-3081 Renamed Cancel status to Aborted
  src/Status/StatusCard/StatusCard.stories.tsx
  src/Status/statuses.ts
Labels: enhancement

#953 TD-3067 Add LazyLoadImage RUI component
  package.json
  src/Card/DetailCard/DetailCard.test.tsx
  src/Card/DetailCard/DetailCard.test.txt
  src/Card/DetailCard/DetailCard.tsx
  src/Card/SummaryCard/SummaryCard.test.tsx
  src/Card/SummaryCard/SummaryCard.test.txt
  src/Card/SummaryCard/SummaryCard.tsx
  src/CardContent/Infographic/Infographic.stories.tsx
  src/CardContent/Infographic/Infographic.test.tsx
  src/CardContent/Infographic/Infographic.test.txt
  src/CardContent/Infographic/Infographic.tsx
  src/LazyLoadImage/LazyLoadImage.stories.tsx
  src/LazyLoadImage/LazyLoadImage.tsx
  src/LazyLoadImage/LazyLoadImage.types.ts
  src/LazyLoadImage/index.ts
  src/index.ts
Labels: enhancement

#955 TD-3098 Create StatusCountTable Component
  src/Status/StatusCountTable/StatusCountTable.stories.tsx
  src/Status/StatusCountTable/StatusCountTable.test.tsx
  src/Status/StatusCountTable/StatusCountTable.tsx
  src/Status/StatusCountTable/StatusCountTable.types.ts
  src/Status/StatusCountTable/index.ts
  src/Status/index.ts
  src/index.ts
Labels: enhancement

#958 bug/Release v8.9.0 - "string can not be used to index object" build error
  src/Status/StatusCountTable/StatusCountTable.tsx
Labels: bug

#960 TD-3097 Status count bar component and useDelayedHover hook
  package.json
  src/Status/StatusCountBar/StatusCountBar.stories.tsx
  src/Status/StatusCountBar/StatusCountBar.test.tsx
  src/Status/StatusCountBar/StatusCountBar.tsx
  src/Status/StatusCountBar/StatusCountBar.types.ts
  src/Status/StatusCountBar/index.ts
  src/Status/StatusCountTable/StatusCountTable.tsx
  src/Status/index.ts
  src/hover/index.ts
  src/hover/useDelayedHover.ts
  src/index.ts
Labels: enhancement
