Repository IPG-Automotive-UK/react-ui, pull requests merged in 2025-02, with the labels that each got.

#1038 Latest corepack
  Dockerfile
Labels: bug, dependencies

#1040 TD-2730 Same file can be uploaded multiple times in ROAD
  package.json
  src/Uploader/useUploader.ts
Labels: bug

#1044 TD-3383 Add disable functionality to the cancel button of the ActionDialog
  src/ActionDialog/ActionDialog.stories.tsx
  src/ActionDialog/ActionDialog.test.tsx
  src/ActionDialog/ActionDialog.tsx
  src/ActionDialog/ActionDialog.types.ts
Labels: enhancement

#1041 TD-223 - Added fix for axis labelling to wrap
  package.json
  src/LinePlot/LinePlot.tsx
  src/LinePlot/LinePlot.types.ts
  src/SurfacePlot/SurfacePlot.tsx
Labels: bug

#1045 Allow installing via git
  package.json
Labels: enhancement

#1039 TD-3368 - Enhanced Vehicle Selector
  src/VehicleSelector/VehicleSelector.stories.tsx
  src/VehicleSelector/VehicleSelector.test.tsx
  src/VehicleSelector/VehicleSelector.tsx
  src/VehicleSelector/VehicleSelector.types.ts
  src/VehicleSelector/VehicleSelector.utils.ts
Labels: enhancement

#1048 TD-3359 Change select and transfer logic on search in the transfer list
  src/TransferList/TransferList.stories.tsx
  src/TransferList/TransferList.test.tsx
  src/TransferList/TransferList.tsx
  src/TransferList/TransferList.types.ts
Labels: enhancement

#1049 TD-3385 Remove Vehicle Select
  src/VehicleSelect/VehicleSelect.spec.tsx
  src/VehicleSelect/VehicleSelect.stories.tsx
  src/VehicleSelect/VehicleSelect.test.tsx
  src/VehicleSelect/VehicleSelect.tsx
  src/VehicleSelect/VehicleSelect.types.ts
  src/VehicleSelect/index.ts
  src/VehicleSelectDialog/VehicleSelectDialog.stories.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.test.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.tsx
  src/VehicleSelectDialog/VehicleSelectDialog.types.ts
  src/index.ts
Labels: enhancement

#1054 TD-3390 Display customer logo in VIRTO Header
  src/AppHeader/AppHeader.stories.tsx
  src/ToggleColorMode/ToggleColorMode.jsx
  src/ToggleColorMode/ToggleColorMode.stories.jsx
  src/ToggleColorMode/ToggleColorMode.test.jsx
  src/ToggleColorMode/index.ts
  src/VirtoAppHeader/VirtoAppHeader.stories.tsx
  src/VirtoAppHeader/VirtoAppHeader.test.tsx
  src/VirtoAppHeader/VirtoAppHeader.tsx
  src/VirtoAppHeader/VirtoAppHeader.types.ts
  src/VirtoAppHeader/index.ts
  src/VirtoAppLayout/VirtoAppLayout.stories.tsx
  src/VirtoAppLayout/VirtoAppLayout.test.tsx
  src/VirtoAppLayout/VirtoAppLayout.tsx
  src/VirtoAppLayout/VirtoAppLayout.types.ts
  src/index.ts
  static/DevelLogo.svg
Labels: enhancement

#1056 TD-3389 Updates to UserMenu component
  src/AppHeader/AppHeader.stories.tsx
  src/AppHeader/AppHeader.test.tsx
  src/AppHeader/AppHeader.tsx
  src/AppHeader/AppHeader.types.ts
  src/AppHeader/index.ts
  src/AppLayout/AppLayout.stories.tsx
  src/AppLayout/AppLayout.test.tsx
  src/AppLayout/AppLayout.tsx
  src/AppLayout/AppLayout.types.ts
  src/AppLayout/index.ts
  src/UserMenu/UserMenu.stories.tsx
  src/UserMenu/UserMenu.test.tsx
  src/UserMenu/UserMenu.tsx
  src/UserMenu/UserMenu.types.ts
  src/VirtoAppLayout/VirtoAppLayout.stories.tsx
  src/VirtoAppLayout/VirtoAppLayout.test.tsx
  src/VirtoAppLayout/VirtoAppLayout.tsx
  src/VirtoAppLayout/VirtoAppLayout.types.ts
  src/index.ts
Labels: enhancement

#1058 TD-3416 add auto selection for gates for VehicleSelector in RUI
  src/VehicleSelector/VehicleSelector.stories.tsx
  src/VehicleSelector/VehicleSelector.test.tsx
  src/VehicleSelector/VehicleSelector.tsx
Labels: bug

#1059 TD-3359 TransferList UI improvements
  src/TransferList/TransferList.test.tsx
  src/TransferList/TransferList.tsx
Labels: enhancement
